# Site settings
title: "cogentia"
email: amscott@openmailbox.org
description: "A blog about life, the universe and everything"
baseurl: ""
url: "http://askl56.github.io"
title_description: "A blog about life, the universe and everything"
title_image:
google_analytics: "
disqus_account: askl56
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
github_username:  askl56
google_plus_link: https://plus.google.com/u/0/+AndrewScott56/
quora_link:

# Footer

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
