name: Cogentia.io
markdown: redcarpet
pygments: true
github: https://www.github.com/askl56
about: Ruby on Rails Developer from London
urls:
    - text: github
      url: https://github.com/askl56
    - text: email
      url: mailto:amscott@openmailbox.org
