# Site settings
title: "Cogentia.io"
email: amscott@openmailbox.org
description: "A blog about life, the universe and everything"
baseurl: ""
url: "http://askl56.github.io"
title_description: "A blog about life, the universe and everything"
title_image:
google_analytics: "
disqus_account: askl56
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
github_username:  askl56
google_plus_link: https://plus.google.com/u/0/+AndrewScott56/
quora_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
